version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tickethub-app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis

  redis:
    image: redis:7
    container_name: redis-cache
    ports:
      - "6379:6379"
    restart: unless-stopped
